Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -16,9 +16,18 @@
 image: "python:3.8.13-bullseye"
 
 stages:          # List of stages for jobs, and their order of execution
-  - test
   - changelogtest
-  - release
+  - test
+  - docs
+  - upload
+
+changelog-test-job:
+  stage: changelogtest
+  rules:
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
+  script:
+    - git fetch --all
+    - if [ 0 -eq $(git diff --name-only origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}...${CI_COMMIT_SHA} CHANGELOG.md | wc -l) ]; then exit 1; fi
 
 unit-test-job:   # This job runs in the test stage.
   stage: test    # It only starts when the job in the build stage completes successfully.
@@ -44,16 +53,39 @@ lint-test-job:   # This job also runs in the test stage.
   script:
     - pylint src -d=logging-fstring-interpolation --ignore=edcon_tools # For now ignore
 
-changelog-test-job:
-  stage: changelogtest
-  rules:
-    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
-  script:
-    - git fetch --all
-    - if [ 0 -eq $(git diff --name-only origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}...${CI_COMMIT_SHA} CHANGELOG.md | wc -l) ]; then exit 1; fi
+sphinx-docs:
+    stage: docs
+
+    rules:
+        # The following two rules make sure the job is always executed.
+        - if: '$CI_COMMIT_BRANCH == "develop"'
+        - if: '$CI_COMMIT_BRANCH == "main"'
+        - if: $CI_COMMIT_TAG
+        - if: $CI_MERGE_REQUEST_ID
+        - if: '$CI_PIPELINE_SOURCE == "web"'
+    before_script:
+        - pip install -U pip recommonmark sphinx
+        # - pip3 install -r docs-requirements.txt || echo "no additional requirements for docs specified"
+        - pip3 install .
+    script:
+        - mkdir public
+        - sphinx-apidoc -f -o docs/source src
+        - make -C docs html || exit_code=$?
+        - >
+          if [[ $exit_code -ne 0 ]]; then
+            echo "Sphinx-build failure"
+            exit 1
+          else
+            echo "Sphinx-build success"
+            mv docs/build/html/* public
+          fi
+artifacts:
+        paths:
+            - public
+        when: always
 
 release-job:
-  stage: release
+  stage: upload
   rules:
     - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/ && $CI_COMMIT_REF_PROTECTED == "true"'
   before_script:
@@ -72,7 +104,7 @@ release-job:
 
 pages:
   image: alpine:latest
-  stage: release
+  stage: upload
 
   # rules:
   #   - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/ && $CI_COMMIT_REF_PROTECTED == "true"'
@@ -83,5 +115,5 @@ pages:
     paths:
         - public
 
-  # needs: ["sphinx-docs"]
+  needs: ["sphinx-docs"]
 
