Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -54,34 +54,33 @@ lint-test-job:   # This job also runs in the test stage.
     - pylint src -d=logging-fstring-interpolation --ignore=edcon_tools # For now ignore
 
 sphinx-docs:
-    stage: docs
-    rules:
-        # The following two rules make sure the job is always executed.
-        - if: '$CI_COMMIT_BRANCH == "develop"'
-        - if: '$CI_COMMIT_BRANCH == "main"'
-        - if: $CI_COMMIT_TAG
-        - if: $CI_MERGE_REQUEST_ID
-        - if: '$CI_PIPELINE_SOURCE == "web"'
-    before_script:
-        - pip install -U pip recommonmark sphinx
-        # - pip3 install -r docs-requirements.txt || echo "no additional requirements for docs specified"
-        - pip install .
-    script:
-        - mkdir public
-        - sphinx-apidoc -f -o docs/source src
-        - make -C docs html || exit_code=$?
-        - >
-          if [[ $exit_code -ne 0 ]]; then
-            echo "Sphinx-build failure"
-            exit 1
-          else
-            echo "Sphinx-build success"
-            mv docs/build/html/* public
-          fi
-artifacts:
-        paths:
-            - public
-        when: always
+  stage: docs
+  # rules:
+    # The following two rules make sure the job is always executed.
+    # - if: '$CI_COMMIT_BRANCH == "main"'
+    # - if: $CI_COMMIT_TAG
+    # - if: $CI_MERGE_REQUEST_ID
+    # - if: '$CI_PIPELINE_SOURCE == "web"'
+  before_script:
+    - pip install -U pip recommonmark sphinx
+    # - pip3 install -r docs-requirements.txt || echo "no additional requirements for docs specified"
+    - pip install .
+  script:
+    - mkdir public
+    - sphinx-apidoc -f -o docs/source src
+    - make -C docs html || exit_code=$?
+    - >
+      if [[ $exit_code -ne 0 ]]; then
+        echo "Sphinx-build failure"
+        exit 1
+      else
+        echo "Sphinx-build success"
+        mv docs/build/html/* public
+      fi
+  artifacts:
+    paths:
+      - public
+    when: always
 
 release-job:
   stage: upload
